"""Contratos públicos entre etapas."""

from app.contracts.models import (  # noqa: F401
    SCHEMA_VERSION,
    AdaptedScript,
    Artefacto,
    BaseLicencia,
    Candidate,
    ClaseFuente,
    ComprobacionQA,
    EstadoRender,
    LicenseDecision,
    ModoAjuste,
    PalabraTiempo,
    ProcedenciaIA,
    PublishMetadata,
    PublishResult,
    QAResult,
    RelacionAspecto,
    RenderJob,
    RenderResult,
    SeccionGuion,
    SegmentoTexto,
    SourceAsset,
    SubtitleAsset,
    TipoSeccion,
    TipoTransformacion,
    TransformationElement,
    Transcript,
    Translation,
    VoiceAsset,
)
